baseURL: "https://mvbulutay.github.io/" 
title: Jun Wong
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 1

params:
    description: "I am a PhD student at the University of Chicago working in development and environmental economics."
    author: Jun Wong
    googleAnalyticsID: "G-3D8MPDLYFV"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jun Wong
          subtitle: "I'm a fourth-year PhD student in the **Economics** department at the University of Chicago. My research interests are in **development** and **energy and environmental** economics, particularly in informal environmental and energy markets in LMICs. I have worked as a research assistant at NYU Stern and UC Berkeley Carbon Removal Lab. <br> <small> Photo: [Rey Oliva](https://linktr.ee/reyjroliva) </small>"
          imageUrl: "/headshot.jpg"
          imageWidth: 155
          imageHeight: 167
          imageTitle: Jun Wong
          buttons:
            - name: Research
              url: /research/
            #- name: Courses
            #  url: /courses/
            #- name: Design
            #  url: /design/
            #- name: Newsletter
            #  url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:junwong@uchicago.edu
        #- name: Location
        #  url: /location/
        #- name: Office Hours
        #  url: /officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/junwong97

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Jun Wong"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
